export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const FETCH_DATA_SENDING = 'FETCH_DATA_SENDING'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const FETCH_DATA_SUCCES = 'FETCH_DATA_SUCCES'
